title:            "Webwork.tools: Independent Web-Work and Skyscraper Publishing."
description: #     Describe your website here.

# put your disqus here
disqus_shortname:
reading_time:     true # if true, shows the estimated reading time for a post
words_per_minute: 200
logo:             images/logo.png # logo visible in the topbar
excerpt_separator: <!--more-->
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000

#url: http://127.0.0.1:4000

url: https://infominer.id/web-work

# draw your top menu here
# each item must have a title and a url.
#   To list post categories. use type: 'categories'
#   To create sub categories. add a submenu item
# See the example
menu:
  - title: 'Home'
    url: '/'
  - title: 'Tags'
    url: '/tags'
  - title: "Webwork.tools"
    url: "/webwork.tools/"
  - title: Services
    url: /services/
  - title: ⧉InfoMine⧉
    url: https://infominer.id/
  - title: 'Favorites'
    url: '#'
    submenu:
      - title: GitHub Pages Starter Pack
        url: /github-pages-starter-pack/
      - title: Learn SEO
        url: /learn-seo/
      - title: Mostly Free SEO Tools
        url: /seo-tools/
      - title: Practical PGP
        url: /practical-pgp/
      - title: "IndieWeb"
        url: "https://infominer.id/indieweb/"

# Owner/author information
owner:
  name:           "⧉ Infominer"
  site:           https://infominer.id
  avatar:         info.png
  bio:            "Full-Time Crypto-Curation and Histories ⧉ #Bitcoin #Blockchain #DecentralizedID ⧉ Research, Publishing, #WebWork #Indieweb ⧉"
  email:          infominer@protonmail.com
  # Twitter nick for use in Twitter cards and follow button.
  twitter: infominer33 # if no twitter in this config, the twitter follow button will be removed
  # GitHub nick for use in follow button in author block.
  github: infominer33

# Twitter account associated with the site if different from owner/author twitter account.
# Used in Twitter cards.
twitter:

# Social networking links used in author block underneath posts. Update and remove as you like.
social:
  - title: "github"
    url: "https://github.com/infominer33"
  - title: "linkedin"
    url: "https://br.linkedin.com/in/aronbordin"
  - title: "youtube"
    url: "https://www.youtube.com/channel/UCfnSek-9HPWOx5e2pH7VFgg"
  - label: "Keybase"
    url:  "https://keybase.io/infominer"
  - label: "Twitter"
    url: "https://twitter.com/infominer33"
  - label: "Discord"
    url: "https://discord.gg/ahTuPMY"
  - label: "Telegram"
    url: "https://t.me/InfoMiner33"



# Background image to be tiled on all pages
background: binary.png

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/New_York
locale:      en_US
future:      true
highlighter: rouge
markdown:    kramdown
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 5

# if true, shows the floatting share buttons
float_share: true

# Octopress
# Default extensions
post_ext: md
page_ext: md
# Found in _templates/
post_layout: post
page_layout: page
# Format titles with titlecase?
titlecase: true

include: [".htaccess"]
exclude: ["demo/*", "lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
plugins: 
  - jekyll-paginate
  - jekyll-redirect-from
