publishdir = "docs"
enableEmoji = true
  

baseurl = "https://infominer.id/web-work/"
title = "Webwork.tools"
copyright = "â§‰ Infominer â§‰ CC0 - Public Domain â§‰ Powered by: themes.gohugo.io/indigo via: gohugoio/hugo â§‰"
languageCode = "en-gb"
theme = "indigo"
paginate = 22

[params]
  Author = "Infominer"
  description = "Resources for Independent Webworkers: Web-Publishing, SEO, Static Site Generators, Ubuntu, Git, Practical Crypto."
  Subtitle = "Independent Web-Work and Skyscraper Publishing"
  Avatar = "images/infominer.svg"
  Biography = "Full-Time Crypto-Curation and Histories â§‰ Bitcoin, Blockchain, DecentralizedID â§‰ Research, Publishing, WebWork, Indieweb â§‰ her/him"
  ShowBio = true
  PermalinkText = "ðŸ”—"

  # Contact/social-network identifiers for social icons
  EmailAddress = "infominer@protonmail.com"
  GitHubUser = "infominer33"
  GitLabUser = "infominer33"
  KeybaseUser = "infominer"
  MicroBlogUser = "infominer"
  RedditUser = "infominer33"
  StackOverflowUser = "10793272"
  TwitterUser = "infominer33"

  # These are parameters used for indieweb identity. You should set these along
  # with the above email/social network parameters.
  [params.indieWeb]  
    EmailAddress = "infominer@protonmail.com"
    GitHubUser = "infominer33"
    TwitterUser = "infominer33"
    MicroBlogUser = "infominer"
    Country = "Stateless"
    City = "Marginalized"

  [params.twitter]
    card = "summary_image_large"
    site = "@infominer33"
    creator = "@infominer33"

#https://github.com/kisik21/indigo/commit/e168672487b78bef5070cc0eb70bc5d4e748c707
  [params.endpoints]
  Auth = "https://indieauth.com/auth"
  # To get webmention support, just register at webmention.io and paste the link for endpoint here.
  #Webmention = "https://webmention.io/<yourusername>/webmention"
  # To get micropub support, you'll need to install a Micropub endpoint at your site and put its link there.
  # To get an endpoint with Hugo support, use nanopub: https://github.com/dg01d/nanopub
  # It will probably require some PHP hackery though, as it's fairly basic.
  #Micropub = ""
  # To get microsub support, you can use Aperture from p3k. Either go to https://aperture.p3k.io or self-host it (it's open source!)
  #Microsub = ""

disablePathToLower = true